name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run Playwright tests
      run: npx playwright test
      env:
        SCRAPERAPI_KEY: ${{ secrets.SCRAPERAPI_KEY }}

    - name: Upload Playwright HTML Report
      if: always() 
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report
